name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: crack-parser-394809
  CLUSTER_NAME: cluster-1
  ZONE: us-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    # Authenticate to GCP 
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: crack-parser-394809

    # Configure kubectl to use the GKE cluster
    - name: Authenticate to GKE
      run: |
       gcloud container clusters get-credentials cluster-1 \
          --zone us-central-1 \
          --project crack-parser-394809

    # Apply the deployment manifest

    - name: Apply Kubernetes Deployment
      run: |
       kubectl apply -f deployment.yaml
      
