name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    # Authenticate to GCP 
    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'

    # Configure kubectl to use the GKE cluster
    - name: Authenticate to GKE
      env:
        GOOGLE_PROJECT: crack-parser-394809
      run: |
       gcloud container clusters get-credentials cluster-1 --region us-central1 --project crack-parser-394809
       kubectl apply -f deployment.yaml
       

    # Apply the deployment manifest

  
      
